export const UserActionTypes = {
    LOGIN: 'LOGIN',
    REGISTER: 'REGISTER',
    LOGOUT: 'LOGOUT',
    GOOGLE_LOGIN: 'GOOGLE_LOGIN',
    FACEBOOK_LOGIN: 'FACEBOOK_LOGIN',
    TWITER_LOGIN: 'TWITER_LOGIN',
    INSTAGRAM_LOGIN: 'INSTAGRAM_LOGIN'
};
